name: CD

on:
    push:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    create-version-pr-or-release:
        name: "Create Version PR/Release"
        runs-on: ubuntu-latest
        outputs:
            should-deploy: ${{steps.changesets.outputs.hasChangesets == 'false'}}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Node Environment
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: "npm"
            - name: Install Dependencies
              run: npm ci
            - name: Create Version PR or Github Release
              id: changesets
              uses: changesets/action@v1
              with:
                publish: npx changeset tag
              env:
                GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
            - name: Print Outputs
              run: echo '${{ toJson(steps.changesets.outputs )}}'
            - name: Send A Slack Message For Version PR Updates
              if: steps.changesets.outputs.pullRequestNumber
              uses: slackapi/slack-github-action@v1.24.0
              with:
               payload: |
                {
                    "blocks": [
                    {
                        "type": "section",
                        "text": {
                        "type": "mrkdwn",
                        "text": "* <https://github.com/${{github.repository}}/pull/${{steps.changesets.outputs.pullRequestNumber}}|Version Pull Request>* was updated. Review it and merge it to create a new release and deployment."
                        }
                    }
                    ]
                }
              env:
               SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
               SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
            - name: Set Release Version
              id: get-version
              run: echo "version=${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}" >> $GITHUB_OUTPUT
            - name: Send A Slack Message When A New Release Is Created
              if: steps.changesets.outputs.published == 'true'
              uses: slackapi/slack-github-action@v1.24.0
              with:
               payload: |
                {
                    "blocks": [
                    {
                        "type": "section",
                        "text": {
                        "type": "mrkdwn",
                        "text": "* <https://github.com/${{github.repository}}/releases/tag/v${{steps.get-version.outputs.version}}|Version ${{steps.get-version.outputs.version}}>* Released! Deployment Should Be In Progress."
                        }
                    }
                    ]
                }
              env:
               SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
               SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


    run-tests:
        name: Run Tests
        needs: create-version-pr-or-release
        if: needs.create-version-pr-or-release.outputs.should-deploy == 'true'
        uses: ./.github/workflows/test.yaml
        secrets: inherit
    
    deploy-to-staging:
        name: Deploy (Staging)
        needs: run-tests
        uses: ./.github/workflows/deploy.yaml
        secrets: inherit
        with:
            aws-env: ${{vars.AWS_EB_STAGING_ENV}}
            github-env: 'staging'

    deploy-to-production:
        name: Deploy (Production)
        needs: deploy-to-staging
        uses: ./.github/workflows/deploy.yaml
        secrets: inherit
        with:
            aws-env: ${{vars.AWS_EB_PRODUCTION_ENV}}
            github-env: 'production'
    
